# Generated by Django 4.2.7 on 2024-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable_IOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('period1', models.CharField(max_length=100)),
                ('period2', models.CharField(max_length=100)),
                ('period3', models.CharField(max_length=100)),
                ('period4', models.CharField(max_length=100)),
                ('period5', models.CharField(max_length=100)),
                ('period6', models.CharField(max_length=100)),
                ('period7', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable_IOTCSBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('period1', models.CharField(max_length=100)),
                ('period2', models.CharField(max_length=100)),
                ('period3', models.CharField(max_length=100)),
                ('period4', models.CharField(max_length=100)),
                ('period5', models.CharField(max_length=100)),
                ('period6', models.CharField(max_length=100)),
                ('period7', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable_IT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('period1', models.CharField(max_length=100)),
                ('period2', models.CharField(max_length=100)),
                ('period3', models.CharField(max_length=100)),
                ('period4', models.CharField(max_length=100)),
                ('period5', models.CharField(max_length=100)),
                ('period6', models.CharField(max_length=100)),
                ('period7', models.CharField(max_length=100)),
            ],
        ),
    ]
