# Generated by Django 4.2.7 on 2024-01-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_customusermodel_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='days_present',
            field=models.IntegerField(null=True),
        ),
    ]
