# Generated by Django 4.2.7 on 2024-01-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_customusermodel_days_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
