# Generated by Django 4.2.7 on 2024-01-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_alter_customusermodel_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_teacher',
        ),
    ]
